//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnnovixHRG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealPriceTBL
    {
        public int MealPriceID { get; set; }
        public Nullable<int> MealPriceNum { get; set; }
        public Nullable<int> MealTypeIDD { get; set; }
        public Nullable<int> SeasonHolidayIDD { get; set; }
        public bool IsStopped { get; set; }
    
        public virtual MealTypeTBL MealTypeTBL { get; set; }
        public virtual SeasonPHolidayTBL SeasonPHolidayTBL { get; set; }
    }
}
