//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnnovixHRG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPriceTBL
    {
        public int RoomPriceID { get; set; }
        public Nullable<int> RoomPriceNum { get; set; }
        public Nullable<int> RoomTypeIDD { get; set; }
        public Nullable<int> SeasonHolidayIDD { get; set; }
        public bool IsStopped { get; set; }
    
        public virtual RoomTypeTBL RoomTypeTBL { get; set; }
        public virtual SeasonPHolidayTBL SeasonPHolidayTBL { get; set; }
    }
}
