//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnnovixHRG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonPHolidayTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeasonPHolidayTBL()
        {
            this.MealPriceTBL = new HashSet<MealPriceTBL>();
            this.RoomPriceTBL = new HashSet<RoomPriceTBL>();
        }
    
        public int SeasonHolidayID { get; set; }
        public string SeasonHolidayName { get; set; }
        public Nullable<System.DateTime> SeasonHolidayFrom { get; set; }
        public Nullable<System.DateTime> SeasonHolidayTo { get; set; }
        public bool IsStopped { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealPriceTBL> MealPriceTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomPriceTBL> RoomPriceTBL { get; set; }
    }
}
